1 During wait destroy, instance disappeared.
2 Running cmd (subprocess): mv /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd_del execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
3 CMD mv /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd_del returned: 0 in 0.035s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
4 Deleting instance files /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd_del
5 Deletion of /var/lib/nova/instances/796629c1-ee5d-467d-abc6-6ed90a13e2cd_del complete
6 Took 0.14 seconds to destroy the instance on the hypervisor.
7 Deallocating network for instance _deallocate_network /usr/lib/python2.7/site-packages/nova/compute/manager.py:1824
8 deallocate_for_instance() deallocate_for_instance /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:801
9 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?device_id=796629c1-ee5d-467d-abc6-6ed90a13e2cd -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}05fe57430a1cff2a44b1e95e1a1d67d4a539f6d6 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
10 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 13 X-Openstack-Request-Id: req-f5835dff-8f13-4e0e-8d47-a66c341acf4d Date: Sun, 20 Jun 2021 09:41:06 GMT Connection: keep-alive
11 Instance cache missing network info. _get_preexisting_port_ids /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1659
12 Updating instance_info_cache with network_info: [] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:43
13 Took 0.08 seconds to deallocate network for instance.
14 Aborting claim: [Claim: 512 MB memory, 1 GB disk] abort /usr/lib/python2.7/site-packages/nova/compute/claims.py:120
15 Lock compute_resources acquired by nova.compute.resource_tracker.abort_instance_claim :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
16 Lock compute_resources released by nova.compute.resource_tracker.abort_instance_claim :: held 0.137s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
17 Binding failed for port 1360a484-41dc-4c87-8ad1-fe393750cee7, please check neutron logs for more information. notify_about_instance_usage /usr/lib/python2.7/site-packages/nova/compute/utils.py:284
18 Build of instance 796629c1-ee5d-467d-abc6-6ed90a13e2cd was re-scheduled: Binding failed for port 1360a484-41dc-4c87-8ad1-fe393750cee7, please check neutron logs for more information. _do_build_and_run_instance /usr/lib/python2.7/site-packages/nova/compute/manager.py:1945
19 Lock 796629c1-ee5d-467d-abc6-6ed90a13e2cd released by nova.compute.manager._locked_do_build_and_run_instance :: held 1.926s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
20 Received event network-vif-plugged-ed30b0b2-0af6-473b-9e07-f99f000717ae external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6704
21 Lock 3ad77c0d-f281-408d-8c08-ebd39514a014-events acquired by nova.compute.manager._pop_event :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
22 Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:538
23 No waiting events found dispatching network-vif-plugged-ed30b0b2-0af6-473b-9e07-f99f000717ae pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:554
24 Lock 3ad77c0d-f281-408d-8c08-ebd39514a014-events released by nova.compute.manager._pop_event :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
25 Lock e408299e-7829-48af-bda1-ded6ce677f83-events acquired by nova.compute.manager._pop_event :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
26 Received event network-vif-plugged-5c0e6ba6-6964-4417-ab47-b002c187f081 external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6704
27 Lock e408299e-7829-48af-bda1-ded6ce677f83-events released by nova.compute.manager._pop_event :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
28 Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:538
29 Received event network-vif-plugged-f112b423-8fc2-43fa-ad3c-be2b75678836 external_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:6704
30 No waiting events found dispatching network-vif-plugged-5c0e6ba6-6964-4417-ab47-b002c187f081 pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:554
31 Lock 3ad77c0d-f281-408d-8c08-ebd39514a014-events acquired by nova.compute.manager._pop_event :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
32 Unexpected attempt to pop events during shutdown _pop_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:538
33 Lock 3ad77c0d-f281-408d-8c08-ebd39514a014-events released by nova.compute.manager._pop_event :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
34 No waiting events found dispatching network-vif-plugged-f112b423-8fc2-43fa-ad3c-be2b75678836 pop_instance_event /usr/lib/python2.7/site-packages/nova/compute/manager.py:554
35 Running periodic task SchedulerManager._run_periodic_tasks run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
36 Failed to consume message from queue: [Errno 110] Connection timed out
37 Unexpected exp occurred 1 time(s)... retrying.
38 Unable to connect to AMQP server on controller:5672 after None tries: [Errno 110] Connection timed out
39 AMQP server on controller:5672 is unreachable: connection already closed. Trying again in 1 seconds.
40 Reconnected to AMQP server on controller:5672 via [amqp] client
41 Lock host_instance acquired by nova.scheduler.host_manager.sync_instance_info :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
42 Successfully synced instances from host 'h432-l13'.
43 Lock host_instance released by nova.scheduler.host_manager.sync_instance_info :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
44 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/ports.json?tenant_id=7fe5d95324c448b695017fc3a63492b4&device_id=3ad77c0d-f281-408d-8c08-ebd39514a014 HTTP/1.1 200 1911 0.040389
45 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/networks.json?id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&id=5ecb97e5-77b7-40d5-8e06-36f1ef1a4a3e HTTP/1.1 200 1506 0.050371
46 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/floatingips.json?fixed_ip_address=10.0.0.13&port_id=f112b423-8fc2-43fa-ad3c-be2b75678836 HTTP/1.1 200 232 0.009719
47 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/subnets.json?id=c197d80a-6716-46d7-b6a8-3fbf52d7bfc9 HTTP/1.1 200 757 0.028532
48 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/ports.json?network_id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&device_owner=network%3Adhcp HTTP/1.1 200 1069 0.017319
49 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/floatingips.json?fixed_ip_address=172.30.206.5&port_id=ed30b0b2-0af6-473b-9e07-f99f000717ae HTTP/1.1 200 232 0.019595
50 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/subnets.json?id=382c8931-59c8-4020-ac3f-38a1be805513 HTTP/1.1 200 776 0.030433
51 172.30.205.13 - - [20/Jun/2021 17:41:54] GET /v2.0/ports.json?network_id=5ecb97e5-77b7-40d5-8e06-36f1ef1a4a3e&device_owner=network%3Adhcp HTTP/1.1 200 1073 0.019370
52 Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
53 Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
54 Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
55 Running periodic task ComputeManager._sync_scheduler_instance_info run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
56 Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
57 Auditing locally available compute resources for node h432-l13
58 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
59 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk returned: 0 in 0.100s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
60 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
61 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk returned: 0 in 0.100s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
62 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
63 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk returned: 0 in 0.100s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
64 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
65 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk returned: 0 in 0.102s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
66 Hypervisor: free VCPUs: 158 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:632
67 Hypervisor: assignable PCI devices
68 Hypervisor/Node resource view
69 Lock compute_resources acquired by nova.compute.resource_tracker._update_available_resource :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
70 Total usable vcpus: 160, total allocated vcpus: 2
71 Final resource view: name=h432-l13 phys_ram=785088MB used_ram=3072MB phys_disk=390GB used_disk=21GB total_vcpus=160 used_vcpus=2 pci_stats=[]
72 Compute_service record updated for h432-l13:h432-l13
73 Lock compute_resources released by nova.compute.resource_tracker._update_available_resource :: held 0.177s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
74 Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
75 Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
76 Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
77 Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5741
78 Acquired semaphore refresh_cache-3ad77c0d-f281-408d-8c08-ebd39514a014 lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
79 _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:910
80 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?tenant_id=7fe5d95324c448b695017fc3a63492b4&device_id=3ad77c0d-f281-408d-8c08-ebd39514a014 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
81 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 1696 X-Openstack-Request-Id: req-f3d05933-4ec4-43ec-836c-21600e6d3361 Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
82 REQ: curl -g -i -X GET http://controller:9696/v2.0/networks.json?id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&id=5ecb97e5-77b7-40d5-8e06-36f1ef1a4a3e -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
83 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 1291 X-Openstack-Request-Id: req-50dbdd31-52c0-44f9-81a9-1309bb86745f Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
84 REQ: curl -g -i -X GET http://controller:9696/v2.0/floatingips.json?fixed_ip_address=10.0.0.13&port_id=f112b423-8fc2-43fa-ad3c-be2b75678836 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
85 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 19 X-Openstack-Request-Id: req-5e9c1b47-ed43-4afe-ba43-ebe60e6cda64 Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
86 REQ: curl -g -i -X GET http://controller:9696/v2.0/subnets.json?id=c197d80a-6716-46d7-b6a8-3fbf52d7bfc9 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
87 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 543 X-Openstack-Request-Id: req-7271ee49-f7ed-45c4-ad41-3effaec68053 Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
88 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?network_id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&device_owner=network%3Adhcp -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
89 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 855 X-Openstack-Request-Id: req-bdaf5946-a0a4-4360-9a2a-19c305c79aae Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
90 REQ: curl -g -i -X GET http://controller:9696/v2.0/floatingips.json?fixed_ip_address=172.30.206.5&port_id=ed30b0b2-0af6-473b-9e07-f99f000717ae -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
91 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 19 X-Openstack-Request-Id: req-7403b55d-b9a4-481b-bb1a-1b8be100f94c Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
92 REQ: curl -g -i -X GET http://controller:9696/v2.0/subnets.json?id=382c8931-59c8-4020-ac3f-38a1be805513 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
93 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 562 X-Openstack-Request-Id: req-baefca17-7185-4c81-a445-b49fc2695e1b Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
94 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?network_id=5ecb97e5-77b7-40d5-8e06-36f1ef1a4a3e&device_owner=network%3Adhcp -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
95 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 859 X-Openstack-Request-Id: req-8a350ccb-97a1-4122-86cb-24fd788f5925 Date: Sun, 20 Jun 2021 09:41:54 GMT Connection: keep-alive
96 Updating instance_info_cache with network_info: [VIF({'profile': {}, 'ovs_interfaceid': None, 'preserve_on_delete': False, 'network': Network({'bridge': u'brqcd413b9f-77', 'subnets': [Subnet({'ips': [FixedIP({'meta': {}, 'version': 4, 'type': 'fixed', 'floating_ips': [], 'address': u'10.0.0.13'})], 'version': 4, 'meta': {'dhcp_server': u'10.0.0.2'}, 'dns': [], 'routes': [], 'cidr': u'10.0.0.0/24', 'gateway': IP({'meta': {}, 'version': 4, 'type': 'gateway', 'address': u'10.0.0.1'})})], 'meta': {'injected': False, 'tenant_id': u'7fe5d95324c448b695017fc3a63492b4', 'should_create_bridge': True, 'mtu': 1450}, 'id': u'cd413b9f-77de-462c-afb2-ffc0e91b75c7', 'label': u'int-net'}), 'devname': u'tapf112b423-8f', 'vnic_type': u'normal', 'qbh_params': None, 'meta': {}, 'details': {u'port_filter': True}, 'address': u'fa:16:3e:3c:57:e4', 'active': True, 'type': u'bridge', 'id': u'f112b423-8fc2-43fa-ad3c-be2b75678836', 'qbg_params': None}), VIF({'profile': {}, 'ovs_interfaceid': None, 'preserve_on_delete': False, 'network': Network({'bridge': u'brq5ecb97e5-77', 'subnets': [Subnet({'ips': [FixedIP({'meta': {}, 'version': 4, 'type': 'fixed', 'floating_ips': [], 'address': u'172.30.206.5'})], 'version': 4, 'meta': {'dhcp_server': u'172.30.206.2'}, 'dns': [], 'routes': [], 'cidr': u'172.30.206.0/24', 'gateway': IP({'meta': {}, 'version': 4, 'type': 'gateway', 'address': u'172.30.206.1'})})], 'meta': {'injected': False, 'tenant_id': u'7fe5d95324c448b695017fc3a63492b4', 'should_create_bridge': True, 'mtu': 1500}, 'id': u'5ecb97e5-77b7-40d5-8e06-36f1ef1a4a3e', 'label': u'ext-net'}), 'devname': u'taped30b0b2-0a', 'vnic_type': u'normal', 'qbh_params': None, 'meta': {}, 'details': {u'port_filter': True}, 'address': u'fa:16:3e:1e:d7:da', 'active': True, 'type': u'bridge', 'id': u'ed30b0b2-0af6-473b-9e07-f99f000717ae', 'qbg_params': None})] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:43
97 Releasing semaphore refresh_cache-3ad77c0d-f281-408d-8c08-ebd39514a014 lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
98 Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5803
99 Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
100 Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
101 CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6413
102 Running periodic task SchedulerManager._expire_reservations run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
103 Running periodic task SchedulerManager._run_periodic_tasks run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
104 Received recoverable event from kombu: on_event /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py:674
105 Received recoverable event from kombu: on_event /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py:674
106 AMQP server on controller:5672 is unreachable: timed out. Trying again in 1 seconds.
107 AMQP server on controller:5672 is unreachable: timed out. Trying again in 1 seconds.
108 Received recoverable event from kombu: on_event /usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py:674
109 AMQP server on controller:5672 is unreachable: timed out. Trying again in 1 seconds.
110 Reconnected to AMQP server on controller:5672 via [amqp] client
111 Reconnected to AMQP server on controller:5672 via [amqp] client
112 Reconnected to AMQP server on controller:5672 via [amqp] client
113 AMQP server on controller:5672 is unreachable: timed out. Trying again in 1 seconds.
114 Reconnected to AMQP server on controller:5672 via [amqp] client
115 172.30.205.13 - - [20/Jun/2021 17:42:54] GET /v2.0/ports.json?tenant_id=7fe5d95324c448b695017fc3a63492b4&device_id=e408299e-7829-48af-bda1-ded6ce677f83 HTTP/1.1 200 1065 0.199553
116 172.30.205.13 - - [20/Jun/2021 17:42:54] GET /v2.0/networks.json?id=cd413b9f-77de-462c-afb2-ffc0e91b75c7 HTTP/1.1 200 853 0.034981
117 172.30.205.13 - - [20/Jun/2021 17:42:54] GET /v2.0/floatingips.json?fixed_ip_address=10.0.0.4&port_id=5c0e6ba6-6964-4417-ab47-b002c187f081 HTTP/1.1 200 639 0.007166
118 172.30.205.13 - - [20/Jun/2021 17:42:54] GET /v2.0/subnets.json?id=c197d80a-6716-46d7-b6a8-3fbf52d7bfc9 HTTP/1.1 200 757 0.025125
119 172.30.205.13 - - [20/Jun/2021 17:42:54] GET /v2.0/ports.json?network_id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&device_owner=network%3Adhcp HTTP/1.1 200 1069 0.031483
120 No calling threads waiting for msg_id : 6ce1c903b91a417bb454df0c501ee5e5
121 No calling threads waiting for msg_id : 65cf09d8612a4c839b9136263e17ef0e
122 No calling threads waiting for msg_id : 078e997418234318a435a046299ee32c
123 Running periodic task ComputeManager._run_pending_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
124 Cleaning up deleted instances _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6748
125 There are 0 instances to clean _run_pending_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6757
126 Running periodic task ComputeManager._cleanup_incomplete_migrations run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
127 Cleaning up deleted instances with incomplete migration  _cleanup_incomplete_migrations /usr/lib/python2.7/site-packages/nova/compute/manager.py:6783
128 No calling threads waiting for msg_id : 21e5effab06e492b9156ce6df55025f8
129 172.30.206.92,<local> - - [20/Jun/2021 17:43:08] GET /computeMetadata/v1/instance/id HTTP/1.1 404 176 0.042081
130 172.30.206.92 - - [20/Jun/2021 17:43:08] GET computeMetadata/v1/instance/id HTTP/1.0 404 195 0.046680
131 172.30.206.92,<local> - - [20/Jun/2021 17:43:08] GET /latest/meta-data/instance-id HTTP/1.1 404 176 0.000971
132 172.30.206.92 - - [20/Jun/2021 17:43:08] GET /latest/meta-data/instance-id HTTP/1.0 404 195 0.004956
133 Running periodic task ComputeManager._instance_usage_audit run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
134 Running periodic task ComputeManager._poll_volume_usage run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
135 Running periodic task ComputeManager.update_available_resource run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
136 Auditing locally available compute resources for node h432-l13
137 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
138 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk returned: 0 in 0.092s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
139 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
140 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/3ad77c0d-f281-408d-8c08-ebd39514a014/disk returned: 0 in 0.088s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
141 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
142 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk returned: 0 in 0.076s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
143 Running cmd (subprocess): /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:344
144 CMD /usr/bin/python2 -m oslo_concurrency.prlimit --as=1073741824 --cpu=2 -- env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/e408299e-7829-48af-bda1-ded6ce677f83/disk returned: 0 in 0.080s execute /usr/lib/python2.7/site-packages/oslo_concurrency/processutils.py:374
145 Hypervisor: free VCPUs: 158 _report_hypervisor_resource_view /usr/lib/python2.7/site-packages/nova/compute/resource_tracker.py:632
146 Hypervisor: assignable PCI devices
147 Hypervisor/Node resource view
148 Lock compute_resources acquired by nova.compute.resource_tracker._update_available_resource :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
149 Total usable vcpus: 160, total allocated vcpus: 2
150 Final resource view: name=h432-l13 phys_ram=785088MB used_ram=3072MB phys_disk=390GB used_disk=21GB total_vcpus=160 used_vcpus=2 pci_stats=[]
151 Compute_service record updated for h432-l13:h432-l13
152 Lock compute_resources released by nova.compute.resource_tracker._update_available_resource :: held 0.168s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
153 Running periodic task ComputeManager._poll_unconfirmed_resizes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
154 Running periodic task ComputeManager._poll_rescued_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
155 Running periodic task ComputeManager._heal_instance_info_cache run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
156 Running periodic task ComputeManager._check_instance_build_time run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
157 Rebuilding the list of instances to heal _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5745
158 Starting heal instance info cache _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5741
159 Acquired semaphore refresh_cache-e408299e-7829-48af-bda1-ded6ce677f83 lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:212
160 _get_instance_nw_info() _get_instance_nw_info /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:910
161 Lazy-loading 'info_cache' on Instance uuid e408299e-7829-48af-bda1-ded6ce677f83 obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:895
162 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?tenant_id=7fe5d95324c448b695017fc3a63492b4&device_id=e408299e-7829-48af-bda1-ded6ce677f83 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
163 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 851 X-Openstack-Request-Id: req-6de21586-7e00-4fc1-ab0c-55d933207979 Date: Sun, 20 Jun 2021 09:42:54 GMT Connection: keep-alive
164 REQ: curl -g -i -X GET http://controller:9696/v2.0/networks.json?id=cd413b9f-77de-462c-afb2-ffc0e91b75c7 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
165 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 639 X-Openstack-Request-Id: req-c0c11f70-ea27-44c7-96f7-90df74712325 Date: Sun, 20 Jun 2021 09:42:54 GMT Connection: keep-alive
166 REQ: curl -g -i -X GET http://controller:9696/v2.0/floatingips.json?fixed_ip_address=10.0.0.4&port_id=5c0e6ba6-6964-4417-ab47-b002c187f081 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
167 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 425 X-Openstack-Request-Id: req-c8af852b-aaa6-4514-89e2-3723bf7201cc Date: Sun, 20 Jun 2021 09:42:54 GMT Connection: keep-alive
168 REQ: curl -g -i -X GET http://controller:9696/v2.0/subnets.json?id=c197d80a-6716-46d7-b6a8-3fbf52d7bfc9 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
169 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 543 X-Openstack-Request-Id: req-87e415fb-ba33-403b-bdb6-ff0f21029212 Date: Sun, 20 Jun 2021 09:42:54 GMT Connection: keep-alive
170 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?network_id=cd413b9f-77de-462c-afb2-ffc0e91b75c7&device_owner=network%3Adhcp -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}6647bf1029daf4184a9e89a569f19a381cec7271 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
171 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 855 X-Openstack-Request-Id: req-7c4745fc-6c03-4731-b17a-b22d7fdb9ccb Date: Sun, 20 Jun 2021 09:42:54 GMT Connection: keep-alive
172 Updating instance_info_cache with network_info: [VIF({'profile': {}, 'ovs_interfaceid': None, 'preserve_on_delete': False, 'network': Network({'bridge': u'brqcd413b9f-77', 'subnets': [Subnet({'ips': [FixedIP({'meta': {}, 'version': 4, 'type': 'fixed', 'floating_ips': [IP({'meta': {}, 'version': 4, 'type': 'floating', 'address': u'172.30.206.4'})], 'address': u'10.0.0.4'})], 'version': 4, 'meta': {'dhcp_server': u'10.0.0.2'}, 'dns': [], 'routes': [], 'cidr': u'10.0.0.0/24', 'gateway': IP({'meta': {}, 'version': 4, 'type': 'gateway', 'address': u'10.0.0.1'})})], 'meta': {'injected': False, 'tenant_id': u'7fe5d95324c448b695017fc3a63492b4', 'should_create_bridge': True, 'mtu': 1450}, 'id': u'cd413b9f-77de-462c-afb2-ffc0e91b75c7', 'label': u'int-net'}), 'devname': u'tap5c0e6ba6-69', 'vnic_type': u'normal', 'qbh_params': None, 'meta': {}, 'details': {u'port_filter': True}, 'address': u'fa:16:3e:2e:66:b6', 'active': True, 'type': u'bridge', 'id': u'5c0e6ba6-6964-4417-ab47-b002c187f081', 'qbg_params': None})] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:43
173 Releasing semaphore refresh_cache-e408299e-7829-48af-bda1-ded6ce677f83 lock /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:225
174 Updated the network info_cache for instance _heal_instance_info_cache /usr/lib/python2.7/site-packages/nova/compute/manager.py:5803
175 Running periodic task ComputeManager._reclaim_queued_deletes run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
176 Running periodic task ComputeManager._poll_rebooting_instances run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
177 CONF.reclaim_instance_interval <= 0, skipping... _reclaim_queued_deletes /usr/lib/python2.7/site-packages/nova/compute/manager.py:6413
178 Running periodic task SchedulerManager._expire_reservations run_periodic_tasks /usr/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
179 (170421) accepted ('172.30.205.14', 33904) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:826
180 REQ: curl -g -i -X GET http://controller:35357 -H Accept: application/json -H User-Agent: nova/13.1.0 keystonemiddleware.auth_token/4.4.1 keystoneauth1/2.4.1 python-requests/2.10.0 CPython/2.7.5 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
181 RESP: [300] Date: Sun, 20 Jun 2021 09:43:27 GMT Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 Vary: X-Auth-Token Content-Length: 591 Keep-Alive: timeout=5, max=100 Connection: Keep-Alive Content-Type: application/json
182 Making authentication request to http://controller:35357/v3/auth/tokens get_auth_ref /usr/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py:165
183 REQ: curl -g -i -X GET http://controller:35357/v3 -H Accept: application/json -H User-Agent: nova/13.1.0 keystonemiddleware.auth_token/4.4.1 keystoneauth1/2.4.1 python-requests/2.10.0 CPython/2.7.5 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
184 RESP: [200] Date: Sun, 20 Jun 2021 09:43:28 GMT Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 Vary: X-Auth-Token x-openstack-request-id: req-47cced34-e828-4360-8c4a-90b0423b96f5 Content-Length: 250 Keep-Alive: timeout=5, max=98 Connection: Keep-Alive Content-Type: application/json
185 REQ: curl -g -i -X GET http://controller:35357/v3/auth/tokens -H X-Subject-Token: {SHA1}05fe57430a1cff2a44b1e95e1a1d67d4a539f6d6 -H User-Agent: python-keystoneclient -H Accept: application/json -H X-Auth-Token: {SHA1}fe13350f5507e080cdefadeaa94c3f8116eba5e9 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
186 RESP: [200] Date: Sun, 20 Jun 2021 09:43:28 GMT Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 X-Subject-Token: {SHA1}05fe57430a1cff2a44b1e95e1a1d67d4a539f6d6 Vary: X-Auth-Token x-openstack-request-id: req-0189bf71-f92b-4490-950b-57508cc19454 Content-Length: 2873 Keep-Alive: timeout=5, max=97 Connection: Keep-Alive Content-Type: application/json
187 Reloading cached file /etc/nova/policy.json read_cached_file /usr/lib/python2.7/site-packages/oslo_policy/_cache_handler.py:38
188 Reloaded policy file: /etc/nova/policy.json _load_policy_file /usr/lib/python2.7/site-packages/oslo_policy/policy.py:493
189 Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7f3b1e569210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:699
190 Searching by: {'deleted': False, u'project_id': u'7fe5d95324c448b695017fc3a63492b4'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2061
191 Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'domain': None, 'project_name': u'admin', 'project_domain': None, 'timestamp': '2021-06-20T09:43:28.154040', 'remote_address': '172.30.205.14', 'quota_class': None, 'resource_uuid': None, 'is_admin': True, 'user': u'43b996f08a374a359872ac4444258295', 'service_catalog': [], 'tenant': u'7fe5d95324c448b695017fc3a63492b4', 'read_only': False, 'project_id': u'7fe5d95324c448b695017fc3a63492b4', 'user_id': u'43b996f08a374a359872ac4444258295', 'show_deleted': False, 'roles': [u'admin'], 'user_identity': '43b996f08a374a359872ac4444258295 7fe5d95324c448b695017fc3a63492b4 - - -', 'read_deleted': 'no', 'request_id': 'req-4db52a4b-43e6-43c8-821f-dec2f7a814b4', 'instance_lock_checked': False, 'user_domain': None, 'user_name': u'admin'} enforce /usr/lib/python2.7/site-packages/nova/policy.py:107
192 REQ: curl -g -i -X GET http://controller:9696/v2.0/ports.json?device_id=796629c1-ee5d-467d-abc6-6ed90a13e2cd&device_id=3ad77c0d-f281-408d-8c08-ebd39514a014&device_id=e408299e-7829-48af-bda1-ded6ce677f83 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}05fe57430a1cff2a44b1e95e1a1d67d4a539f6d6 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
193 172.30.205.14 - - [20/Jun/2021 17:43:28] GET /v2.0/ports.json?device_id=796629c1-ee5d-467d-abc6-6ed90a13e2cd&device_id=3ad77c0d-f281-408d-8c08-ebd39514a014&device_id=e408299e-7829-48af-bda1-ded6ce677f83 HTTP/1.1 200 2751 0.045577
194 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 2536 X-Openstack-Request-Id: req-5e849a06-b0a3-4f35-a30a-8fec0b4e2db9 Date: Sun, 20 Jun 2021 09:43:28 GMT Connection: keep-alive
195 REQ: curl -g -i -X GET http://controller:9696/v2.0/security-groups.json?id=b059babb-88bb-4cac-be72-07a559099114 -H User-Agent: python-neutronclient -H Accept: application/json -H X-Auth-Token: {SHA1}05fe57430a1cff2a44b1e95e1a1d67d4a539f6d6 _http_log_request /usr/lib/python2.7/site-packages/keystoneauth1/session.py:248
196 172.30.205.14 - - [20/Jun/2021 17:43:28] GET /v2.0/security-groups.json?id=b059babb-88bb-4cac-be72-07a559099114 HTTP/1.1 200 2492 0.022188
197 RESP: [200] Content-Type: application/json; charset=UTF-8 Content-Length: 2277 X-Openstack-Request-Id: req-51b2574b-ff56-40f3-bb71-62aa4c31a153 Date: Sun, 20 Jun 2021 09:43:28 GMT Connection: keep-alive
198 172.30.205.14 GET /v2.1/7fe5d95324c448b695017fc3a63492b4/servers/detail?limit=21&project_id=7fe5d95324c448b695017fc3a63492b4 HTTP/1.1 status: 200 len: 5864 time: 1.0962970
199 172.30.205.14 - - [20/Jun/2021 17:43:29] GET /v2.0/ports.json?device_id=796629c1-ee5d-467d-abc6-6ed90a13e2cd&device_id=3ad77c0d-f281-408d-8c08-ebd39514a014&device_id=e408299e-7829-48af-bda1-ded6ce677f83 HTTP/1.1 200 2751 0.034294
200 172.30.205.14 - - [20/Jun/2021 17:43:29] GET /v2.0/floatingips.json?tenant_id=7fe5d95324c448b695017fc3a63492b4&port_id=5c0e6ba6-6964-4417-ab47-b002c187f081&port_id=ed30b0b2-0af6-473b-9e07-f99f000717ae&port_id=f112b423-8fc2-43fa-ad3c-be2b75678836 HTTP/1.1 200 639 0.011708
